// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop_DataA.Data;

#nullable disable

namespace Shop_DataA.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230530134347_newApp")]
    partial class newApp : newAppBase
    {
    }
}
